project:
  type: website
  output-dir: docs
website:
  title: "Trailhead Data Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/TrailheadDS/blog
      - icon: mastodon
        href: https://mastodon.social/explore
format:
  html:
    theme: minty
    css: styles.css



